<a href="https://colab.research.google.com/github/Sagarika-Ande/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
l=list(range(5))
print(l)

[0, 1, 2, 3, 4]


In [ ]:
[str(c) for c in l]

['0', '1', '2', '3', '4']

In [ ]:
[float(c) for c in l]


[0.0, 1.0, 2.0, 3.0, 4.0]

In [ ]:
np.full((3,5),7.0)

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
x1=np.array([1,2,3,4,5])
x1[-1]


np.int64(5)

In [ ]:
x2= np.array([[1,2,3],[4,5,6],[7,8,9]])
x2[0,2]=2
x2
x2[2,-1]

np.int64(9)

In [ ]:
# prompt: x=np.arange(10)

import numpy as np
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[ : : -1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr1=[10,20,30]
arr2=[40,50,60]
arr3=[70,80,90,]
np.concatenate([arr1,arr2,arr3])




array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr=np.array([[1,2,3],[5,6,7]])
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)

<built-in method reshape of numpy.ndarray object at 0x78002ce5cf90>


In [ ]:
y=np.array([1,2,3,4,5,6,7,8,9])
print(y.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x=np.array([[1,2,3,4],[6,7,8,9]])
y=np.transpose(x)
print(y)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=arr1*arr2
print(arr3)

[ 4 10 18]


In [87]:
import numpy as np
np.__version__

'2.0.2'

In [90]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
[str(c) for c in l]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [94]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [107]:
arr1=np.ones(3,dtype=bool)
arr1

array([ True,  True,  True])

In [100]:
arr2=np.linspace(1,10,2)
arr2

array([ 1., 10.])

In [103]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [104]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [119]:
x=np.array([1,2,3,4,5])
y=np.prod(x)
print(y)

120


In [120]:
import pandas as pd
pd.__version__

'2.2.2'

In [125]:
data=pd.Series({1:'pink',2:'red',3:'green'})
data

1     pink
2      red
3    green
dtype: object

In [131]:
data=({'empid':[101,102,103],
        'empname':['sony','priya','madhu']})
x=pd.DataFrame(data)
print(x)

   empid empname
0    101    sony
1    102   priya
2    103   madhu


# New Section

In [139]:
df = pd.read_csv('/content/people.csv')
print(df.head())

   ID     Name  Age      City
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   22    Sydney
3   4    David   28   Toronto
4   5      Eva   35    Berlin


In [140]:
print(df.tail())

   ID     Name  Age      City
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   22    Sydney
3   4    David   28   Toronto
4   5      Eva   35    Berlin


In [141]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      5 non-null      int64 
 1   Name    5 non-null      object
 2   Age     5 non-null      int64 
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None


In [142]:
print(df.describe())

             ID        Age
count  5.000000   5.000000
mean   3.000000  28.000000
std    1.581139   4.949747
min    1.000000  22.000000
25%    2.000000  25.000000
50%    3.000000  28.000000
75%    4.000000  30.000000
max    5.000000  35.000000


In [148]:
print(pd.read_csv('people.csv'))

   ID     Name  Age      City
0   1    Alice   25  New York
1   2      Bob   30    London
2   3  Charlie   22    Sydney
3   4    David   28   Toronto
4   5      Eva   35    Berlin


In [152]:
df['ID']
df['Name']

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [153]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [154]:
df.isnull()

ID   Name    Age   City
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

In [156]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 22, 28],
    'City': ['NYC', 'London', 'Sydney', 'Toronto']
}

df = pd.DataFrame(data)

In [160]:
df.iloc[0]       # First row
df.iloc[1:3]     # Rows from index 1 to 2
df.iloc[:, 0]

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [161]:
df.loc[0]                   # Row with index label 0
df.loc[0:2, ['Name', 'Age']]

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22

In [163]:
df.at[1, 'Name']     # Faster, label-based access
df.iat[1, 0]         # Faster, position-based access

'Bob'

In [164]:
df[df['City'].isin(['NYC', 'London'])]

Name  Age    City
0  Alice   25     NYC
1    Bob   30  London

In [165]:
np.random.rand(3)            # 1D array of 3 random numbers
np.random.rand(2, 3)

array([[0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [166]:
np.random.randint(1, 10)         # Single random int from 1 to 9
np.random.randint(1, 100, 5)     # Array of 5 random ints
np.random.randint(10, size=(2, 3))  # 2x3 array of ints (0 to 9)


array([[5, 9, 8],
       [9, 4, 3]])

In [167]:
np.random.randn(4)           # 1D array from normal distribution
np.random.randn(2, 3)        # 2x3 array

array([[2.00815709, 0.22988654, 0.60489373],
       [1.62715982, 1.59456053, 0.23043417]])

In [168]:
np.random.choice([10, 20, 30, 40])    # Pick one
np.random.choice([1, 2, 3], size=5, replace=True)  # Pick 5 with replacement


array([1, 3, 3, 1, 3])

In [169]:
np.random.seed(42)          # Set seed
np.random.rand(3)           # Will always give the same result every time you run

array([0.37454012, 0.95071431, 0.73199394])