<a href="https://colab.research.google.com/github/Sagarika-Ande/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
l=list(range(5))
print(l)

[0, 1, 2, 3, 4]


In [ ]:
[str(c) for c in l]

['0', '1', '2', '3', '4']

In [ ]:
[float(c) for c in l]


[0.0, 1.0, 2.0, 3.0, 4.0]

In [ ]:
np.full((3,5),7.0)

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
x1=np.array([1,2,3,4,5])
x1[-1]


np.int64(5)

In [ ]:
x2= np.array([[1,2,3],[4,5,6],[7,8,9]])
x2[0,2]=2
x2
x2[2,-1]

np.int64(9)

In [ ]:
# prompt: x=np.arange(10)

import numpy as np
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[ : : -1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr1=[10,20,30]
arr2=[40,50,60]
arr3=[70,80,90,]
np.concatenate([arr1,arr2,arr3])




array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr=np.array([[1,2,3],[5,6,7]])
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)

<built-in method reshape of numpy.ndarray object at 0x78002ce5cf90>


In [ ]:
y=np.array([1,2,3,4,5,6,7,8,9])
print(y.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x=np.array([[1,2,3,4],[6,7,8,9]])
y=np.transpose(x)
print(y)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=arr1*arr2
print(arr3)

[ 4 10 18]


In [87]:
import numpy as np
np.__version__

'2.0.2'

In [90]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
[str(c) for c in l]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [94]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [107]:
arr1=np.ones(3,dtype=bool)
arr1

array([ True,  True,  True])

In [100]:
arr2=np.linspace(1,10,2)
arr2

array([ 1., 10.])

In [103]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [104]:
np.full([2,3],5)

array([[5, 5, 5],
       [5, 5, 5]])

In [119]:
x=np.array([1,2,3,4,5])
y=np.prod(x)
print(y)

120


In [120]:
import pandas as pd
pd.__version__

'2.2.2'

In [125]:
data=pd.Series({1:'pink',2:'red',3:'green'})
data

1     pink
2      red
3    green
dtype: object

In [131]:
data=({'empid':[101,102,103],
        'empname':['sony','priya','madhu']})
x=pd.DataFrame(data)
print(x)

   empid empname
0    101    sony
1    102   priya
2    103   madhu


# New Section